#pragma once
#include "GameObject.h"


#define MARIOBULLET_GRAVITY			0.002f

#define MARIOBULLET_BBOX_WIDTH 9*3
#define MARIOBULLET_BBOX_HEIGHT 9*3
#define MARIOBULLET_BBOX_HEIGHT_DIE 9

#define MARIOBULLET_STATE_WALKING 100
#define MARIOBULLET_STATE_DIE 200

#define MARIOBULLET_ANI_WALKING 0
#define MARIOBULLET_ANI_DIE 1

#define MARIO_WALKING_SPEED		0.1f 
//0.1f
#define MARIO_JUMP_SPEED_Y		0.3f
#define MARIO_JUMP_DEFLECT_SPEED 0.4f
#define MARIO_GRAVITY			0.002f
#define MARIO_DIE_DEFLECT_SPEED	 0.5f

#define MARIO_STATE_IDLE			0
#define MARIO_STATE_WALKING_RIGHT	100
#define MARIO_STATE_WALKING_LEFT	200
#define MARIO_STATE_JUMP			300
#define MARIO_STATE_DIE				400
#define MARIO_STATE_SITDOWN			500
#define MARIO_STATE_JUMP_HIGH			600

#define MARIO_ANI_BIG_IDLE_RIGHT		0
#define MARIO_ANI_BIG_IDLE_LEFT			1
#define MARIO_ANI_SMALL_IDLE_RIGHT		2
#define MARIO_ANI_SMALL_IDLE_LEFT			3


#define MARIO_ANI_BIG_WALKING_RIGHT			4
#define MARIO_ANI_BIG_WALKING_LEFT			5
#define MARIO_ANI_SMALL_WALKING_RIGHT		6
#define MARIO_ANI_SMALL_WALKING_LEFT		7


#define MARIO_ANI_DIE				8


#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2

#define MARIO_BIG_BBOX_WIDTH  15
#define MARIO_BIG_BBOX_HEIGHT 27

#define MARIO_BIG_SITDOWN_BBOX_WIDTH  14
#define MARIO_BIG_SITDOWN_BBOX_HEIGHT 19

#define MARIO_SMALL_BBOX_WIDTH  13
#define MARIO_SMALL_BBOX_HEIGHT 15

#define MARIO_BIG_TAIL_BBOX_WIDTH  21
#define MARIO_BIG_TAIL_BBOX_HEIGHT 28

#define MARIO_BIG_TAIL_SITDOWN_BBOX_WIDTH  22
#define MARIO_BIG_TAIL_SITDOWN_BBOX_HEIGHT 19



#define GOOMBA_WALKING_SPEED 0.1f;

#define GOOMBA_BBOX_WIDTH 16
#define GOOMBA_BBOX_HEIGHT 15
#define GOOMBA_BBOX_HEIGHT_DIE 9

#define BULLET_STATE_FLY_RIGHT 100
#define BULLET_STATE_FLY_LEFT 200
#define GOOMBA_STATE_DIE 300

#define GOOMBA_ANI_WALKING 0
#define GOOMBA_ANI_DIE 1




#define MARIO_UNTOUCHABLE_TIME 5000



class MarioBullet : public CGameObject
{
	virtual void GetBoundingBox(float& left, float& top, float& right, float& bottom);
	virtual void Update(DWORD dt, vector<LPGAMEOBJECT>* coObjects);
	virtual void Render();


public:
	virtual void SetState(int state);
};
